### 1. User and Role Management

### API 1 User Registration  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"active"
}




### API 2 User Register Missing Name   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",    
    "status":"active"
}


### API 3 User Register Missing Email  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",   
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"active"

}


### API 4 User Register Missing Password  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",   
    "role":"ADMIN",
    "status":"active"

}

### API 5 User Register Missing Role   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "status":"active"

}


### API 6 User Register Invalid Role   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"INVALIDROLE",
    "status":"active"
}




### API 18 User Register Missing Status   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN"
    
}


### API 19 User Register Invalid Status   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"shdfkhsakf"
}





### API 7 User Register Weak Password   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"week",
    "role":"ADMIN"
}



### API 8 User Register Invalid Email Format    - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45ssscasgjfd",
    "password":"premkakkkssk",
    "role":"ADMIN"
}




### API 9 User Register User Duplicate Email   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
        "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN"
}





### API 10 User Register User Empty  Body   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{

}



### API 11 User Login Success - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45"
}



### API 12 User Login (Empty  Body) - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{

}



### API 13 User Login Missing Email  - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{

    "password":"premkumar45"
}


### API 14 User Login Missing Password - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumarjp45@gmail.com"
   
}

### API 15 User Login Email Invalid Format -completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumaskdakhsdkashkfh",
    "password":"premkumar45"
   
}


### API 16 User Login Invalid User - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumas@gamil.com",
    "password":"premkumar45"
   
}



### API 17 User Login Incorrect Password - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
   "email":"premkumarjp45@gmail.com",
    "password":"premkumar45dasdasddasfad"
   
}





### 2. Financial Records Management
/*/
Creating records
Viewing records
Updating records
Deleting records
Filtering records based on criteria such as date, category, or type
categories like Salary , food , Travel
/*/

### Admin: Can create, update, and manage records and users


### API 20 Get All users  with Admin JWT TOKEN  -completed
GET http://localhost:5000/api/finance/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA



### API 21 Get All users  with Admin Without JWT TOKEN -completed
POST http://localhost:5000/api/finance/users



### API 22 Get All users  with Admin Invalid JWT TOKEN - completed
POST http://localhost:5000/api/finance/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW

### API 23 Get All users  with Non - Admin JWT TOKEN  -completed
POST http://localhost:5000/api/finance/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9W1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA



/*/

I used Sample Data 
[
  {
    "name": "Rahul Sharma",
    "email": "rahul.sharma01@gmail.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Sneha Reddy",
    "email": "sneha.reddy02@yahoo.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Arjun Verma",
    "email": "arjun.verma03@outlook.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Kiran Kumar",
    "email": "kiran.kumar04@gmail.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Meena Iyer",
    "email": "meena.iyer05@yahoo.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Vikas Singh",
    "email": "vikas.singh06@outlook.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Pooja Nair",
    "email": "pooja.nair07@gmail.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Rohit Gupta",
    "email": "rohit.gupta08@yahoo.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Anita Desai",
    "email": "anita.desai09@outlook.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Deepak Yadav",
    "email": "deepak.yadav10@gmail.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Swathi Rao",
    "email": "swathi.rao11@yahoo.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Manoj Kumar",
    "email": "manoj.kumar12@outlook.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Kavya Reddy",
    "email": "kavya.reddy13@gmail.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Suresh Babu",
    "email": "suresh.babu14@yahoo.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Divya Sharma",
    "email": "divya.sharma15@outlook.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Naresh Patel",
    "email": "naresh.patel16@gmail.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Anjali Singh",
    "email": "anjali.singh17@yahoo.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Ravi Teja",
    "email": "ravi.teja18@outlook.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Lakshmi Devi",
    "email": "lakshmi.devi19@gmail.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Gopal Krishna",
    "email": "gopal.krishna20@yahoo.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Keerthi Rani",
    "email": "keerthi.rani21@outlook.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Praveen Kumar",
    "email": "praveen.kumar22@gmail.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Sindhu Priya",
    "email": "sindhu.priya23@yahoo.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  },
  {
    "name": "Teja Reddy",
    "email": "teja.reddy24@outlook.com",
    "password": "premkumar45",
    "role": "VIEWER",
    "status": "active"
  },
  {
    "name": "Harish Kumar",
    "email": "harish.kumar25@gmail.com",
    "password": "premkumar45",
    "role": "ANALYST",
    "status": "active"
  }
]

/*/



### API 24 Get User userId  with Admin JWT TOKEN -completed
GET http://localhost:5000/api/finance/users/69d25ce4ac80a5bd428951c5
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA


### API 25 Get User userId  without  Admin JWT TOKEN  --completed
GET http://localhost:5000/api/finance/users/69d25ce4ac80a5bd428951c5




### API 26 Update User Role with  userId  --   Admin JWT TOKEN  --completed 
POST http://localhost:5000/api/finance/users/69d25ce4ac80a5bd428951c5
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type:application/json
{
  "role":"ANALYST"
}



### API 27 Update User Status with  userId  --   Admin JWT TOKEN -completed
POST http://localhost:5000/api/finance/users/69d25ce4ac80a5bd428951c5/inactive
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type:application/json

{
  "status":"inactive"
}





### API 28 Delete User with  userId  --   Admin JWT TOKEN -completed
DELETE http://localhost:5000/api/finance/users/69d25ce4ac80a5bd428951c5
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA