### 1. User and Role Management

### API 1 User Registration  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"active"
}




### API 2 User Register Missing Name   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",    
    "status":"active"
}


### API 3 User Register Missing Email  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",   
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"active"

}


### API 4 User Register Missing Password  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",   
    "role":"ADMIN",
    "status":"active"

}

### API 5 User Register Missing Role   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "status":"active"

}


### API 6 User Register Invalid Role   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"INVALIDROLE",
    "status":"active"
}




### API 18 User Register Missing Status   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN"
    
}


### API 19 User Register Invalid Status   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"shdfkhsakf"
}





### API 7 User Register Weak Password   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"week",
    "role":"ADMIN"
}



### API 8 User Register Invalid Email Format    - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45ssscasgjfd",
    "password":"premkakkkssk",
    "role":"ADMIN"
}




### API 9 User Register User Duplicate Email   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
        "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN"
}





### API 10 User Register User Empty  Body   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{

}



### API 11 User Login Success - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45"
}



### API 12 User Login (Empty  Body) - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{

}



### API 13 User Login Missing Email  - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{

    "password":"premkumar45"
}


### API 14 User Login Missing Password - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumarjp45@gmail.com"
   
}

### API 15 User Login Email Invalid Format -completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumaskdakhsdkashkfh",
    "password":"premkumar45"
   
}


### API 16 User Login Invalid User - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumas@gamil.com",
    "password":"premkumar45"
   
}



### API 17 User Login Incorrect Password - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
   "email":"premkumarjp45@gmail.com",
    "password":"premkumar45dasdasddasfad"
   
}





### 2. Financial Records Management
/*/
Creating records
Viewing records
Updating records
Deleting records
Filtering records based on criteria such as date, category, or type
categories like Salary , food , Travel
/*/

### Admin: Can create, update, and manage records and users


### API 20 Get All users  with Admin JWT TOKEN 
POST http://localhost:5000/api/finance/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA



### API 21 Get All users  with Admin Without JWT TOKEN -completed
POST http://localhost:5000/api/finance/users



### API 22 Get All users  with Admin Invalid JWT TOKEN - completed
POST http://localhost:5000/api/finance/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW

### API 23 Get All users  with Non - Admin JWT TOKEN 
POST http://localhost:5000/api/finance/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9W1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA



